[IV-24-25]
pablotl0/turismo pull request #1
Opened 2024-09-26 07:11 UTC by pablotl0

1. ¿Se trata de un problema real del que se tenga conocimiento personal?
Sí: La reducción del consumo energético en el hogar es un problema real y conocido. 

2. ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
Sí: Debido a  la accesibilidad para usuarios que deseen acceder a los datos desde cualquier lugar y el almacenamiento y procesamiento de grandes cantidades de datos.

3. ¿La solución requiere una cierta cantidad de lógica de negocio, en vez de solucionarse sólo almacenando y buscando?
Sí: La solución no solo se trata de almacenar y buscar datos de consumo energético. Requiere una lógica de negocio para analizar los patrones de uso, optimizar el consumo de energía, generar recomendaciones personalizadas y posiblemente predecir el consumo futuro con base en ciertos parámetros (como el clima o las tarifas horarias). 

4 ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
Sí: Se pueden obtener datos generales sobre patrones de consumo energético típicos para diferentes tipos de hogares (número de habitantes, tamaño del hogar, tipo de electrodomésticos, etc.). También sobre tarifas energéticas y condiciones climáticas: Las tarifas de energía eléctrica y las condiciones climáticas son datos que pueden obtenerse de fuentes públicas, como proveedores de energía locales o servicios meteorológicos.

2024-09-27 10:23 UTC, JJ reviewed
En todo caso, no parece que haya ningún problema definido que vaya más allá de leer y publicar.

2024-09-27 10:23 UTC, JJ commented on README.md
> +En el contexto actual de creciente preocupación por la sostenibilidad, el aumento de los costos energéticos y la necesidad urgente de mitigar el impacto ambiental, la optimización del consumo energét
¿La optimización del consumo no es una fuente física externa? Aunque resuelvas el problema, no vas a poder crear tests que lo comprueban...
"Cómo y cuando" se consume también es un problema físico.

2024-09-27 10:23 UTC, JJ commented on README.md
> +Para la implementación del proyecto usaré Python.
Nadie ha dicho que habléis del lenguaje.

2024-09-27 11:44 UTC, pablotl0 commented
@JJ

2024-09-27 11:50 UTC, pablotl0 commented
¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
La solución requiere el desarrollo de una plataforma en línea que gestione datos en tiempo real sobre afluencia de visitantes y condiciones ambientales, facilitando así una mejor gestión del turismo.

¿La solución requiere una cierta cantidad de lógica de negocio, en vez de solucionarse sólo almacenando y buscando?
La solución implica lógica de negocio para distribuir visitantes, enviar alertas sobre saturación, y personalizar recomendaciones de rutas.

¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
Los datos necesarios (como información sobre rutas, afluencia de visitantes, y condiciones ambientales) están disponibles a través de portales de datos abiertos, como los de la Junta de Andalucía y el Ayuntamiento de Granada.

2024-09-27 11:51 UTC, pablotl0 commented
@JJ

2024-09-27 18:04 UTC, JJ commented
> ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube? La solución requiere el desarrollo de una plataforma en línea que gestione datos en tiempo real sobre afluencia de visitantes y condiciones ambientales, facilitando así una mejor gestión del turismo.
> 
> ¿La solución requiere una cierta cantidad de lógica de negocio, en vez de solucionarse sólo almacenando y buscando? La solución implica lógica de negocio para distribuir visitantes, enviar alertas sobre saturación, y personalizar recomendaciones de rutas.
> 
> ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca? Los datos necesarios (como información sobre rutas, afluencia de visitantes, y condiciones ambientales) están disponibles a través de portales de datos abiertos, como los de la Junta de Andalucía y el Ayuntamiento de Granada.

En el cuerpo del PR, por favor.

2024-09-27 18:14 UTC, JJ reviewed
En general, no es complicado que aprendáis a usar una metodología como *design thinking* (lo que hicimos en el juego de rol) para no sólo identificar un problema, sino identificar qué tipos de problemas serían aceptables para esta asignatura. El no usar una metodología es un algoritmo que no termina: puedes entregar un número infinito de posibles "ideas", que si no han seguido una metodología adecuada pueden ser perfectamente inválidas.
Si no quieres aprender la metodología, o hacer de nuevo el juego de rol por tu cuenta (los ficheros están disponibles), simplemente lee tranquilamente [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n) o entiende por qué estoy pidiendo la descripción de un problema: porque es un documento sobre el que empezar a trabajar para poder desarrollar código que lo resuelva. ¿Te parece que con lo que has escrito una persona cualquiera podría desarrollar código que podría siquiera apuntar a resolverlo? ¿Te parece que habría alguna forma de que ese código se testeara? ¿Cómo? ¿Midiendo la degradación del medio ambiente? 
Tendríais que intentar ver este objetivo como parte de un proyecto, el inicio, y visualizaros a vosotros mismos o incluso mejor, a otra persona desconocida, desarrollando a partir de lo escrito. Es la única forma de que podáis describir un problema para una persona o grupo de personas determinado con la que se pueda trabajar.
Si el medio ambiente es tu preocupación, en el mismo guión aparecen enlazados portales de datos abiertos, algunos con datos bien estructurados (sobre los que tendrías que aplicar algún tipo de procesamiento no trivial, que resolviera el problema para alguien) o poco estructurados (donde el problema consistiría en extraer y validar esos datos). Te animo a que le eches un vistazo a ver si podemos encontrar un problema sobre el que puedas trabajar.

2024-09-27 18:14 UTC, JJ commented on README.md
> +Para la implementación del proyecto usaré Python.
Debes mirar todos los comentarios y resolverlos o bien cambiando (o borrando) la línea o bien pinchando en "resolver" explicando dónde lo habéis hecho.

2024-09-27 18:14 UTC, JJ commented on README.md
> +Muchos turistas no tienen acceso a información sobre las capacidades de carga de cada área natural ni sobre las mejores prácticas para un turismo responsable. Esto resulta en decisiones de visita que
No veo que sea
1. Un problema del que tengas conocimiento personal.
2. Quién es realmente el cliente.
3. Dónde están los datos para hacer esto ni qué vas a hacer con ellos.

2024-09-27 18:14 UTC, JJ commented on .gitignore
> +#
Esto no es ni un fichero de configuración ni uno que tenga que revisar. Los PRs son para que yo (o el equipo de trabajo) revise el trabajo hecho. Si haces esto, aparte de caer en uno de [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#sobre-la-entrega-y-presentaci%C3%B3n)

> ¿De qué forma el fichero .gitignore y la licencia forman parte de la configuración?

Sólo estás añadiendo *ruido* a la revisión, de forma que no se hace evidente que entiendas el objetivo de la misma.

2024-09-30 08:16 UTC, pablotl0 commented
@JJ quería solicitar una revisión, muchas gracias.

2024-10-03 06:44 UTC, JJ requested changes
En la [explicación(http://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicación) te dice en qué consiste la configuración. Por favor, sigue el guión y no pongáis documentación si no entendéis qué es lo que se pide y por qué.
Perdona que lo lo haya revisado a tiempo. Cuando se me pase, simplemente hazme otra referencia a las 24 o 48 horas.

2024-10-03 06:44 UTC, JJ commented on README.md
> +La licencia del proyecto es  [`/LICENSE`](./LICENSE).
esto no es la configuración

2024-10-03 07:45 UTC, pablotl0 commented
@JJ revision

2024-10-03 07:50 UTC, JJ requested changes
Sin usuario no hay historia de usuario, así que es conveniente que lo pongáis desde el principio.

2024-10-03 07:50 UTC, JJ commented on .gitignore
> +# Built Visual Studio Code Extensions
Esto no es parte del objetivo. Deberíais "sacar" esto a la rama principal y hacer un rebase. Si no sabéis como hacerlo, simplemente borra el fichero de aquí, porque no forma parte de este objetivo.

2024-10-03 07:50 UTC, JJ commented on README.md
> +En la actualidad, los datos ambientales son cruciales para entender la salud pública, la planificación urbana y el bienestar general. Sin embargo, se presenta una serie de desafíos al intentar obtene
Aunque la idea está clara, formalmente no has formulado quién va a ser el cliente y por tanto según desarrollo ágil es imposible ir adelante. Eso también indica que no has seguido la metodología de design thinking.

2024-10-03 07:50 UTC, JJ commented on README.md
> +El proyecto se centra en la investigación y análisis de los datos ambientales de la ciudad, con el fin de entender cómo estos afectan la calidad de vida y varían a lo largo del tiempo. La meta es obt
Como no tienes un cliente, no tienes realmente un problema. El problema puede ser simplemente analizar esos datos que están en un fichero de texto determinado, pero deberías aclararlo así. Diferentes personas (una persona con alergias, un periodista de datos, una persona de un ayuntamiento que no tenga medidor ambiental) van a tener diferentes necesidades.

2024-10-03 07:50 UTC, JJ commented on docs/objetivo-0.md
> +## Subo la Clave Pública a GitHub
Ya sé como se hace. Lo que deberías haber puesto aquí es un pantallazo de que efectivamente está aquí la clave.

2024-10-04 10:18 UTC, pablotl0 commented
@JJ Listo para revisión

2024-10-04 15:29 UTC, JJ reviewed
Por favor, lee y resuelve *todos* los comentarios.

2024-10-04 15:29 UTC, JJ commented on README.md
> +En la actualidad, los datos ambientales son cruciales para entender la salud pública, la planificación urbana y el bienestar general. Sin embargo, se presenta una serie de desafíos al intentar obtene
No has resuelto los comentarios, o cambiando la línea en la que están o indicando dónde se han resuelto. Hasta que no se resuelvan los comentarios no se puede aprobar.

2024-10-05 10:46 UTC, pablotl0 commented
> Por favor, lee y resuelve _todos_ los comentarios.

Parece que no se habia actualizado bien el documento.

<img width="351" alt="actualizacion-ob0" src="https://github.com/user-attachments/assets/91e371de-696e-43b5-bfe8-672ca7fd480b">

En cada apartado hecho referencia a los clientes que se ven afectados por el problema

2024-10-05 10:52 UTC, JJ commented
> * [ ]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Si, soy un periodista interesado en entender y comunicar estos datos.
> 
>     * [ ]  ¿Se trata de un problema que para solucionar requiera el despliegue  de una aplicación en la nube?
>       Sí, la aplicación en la nube sería ideal para centralizar datos dispersos y permitir acceso y análisis en tiempo real.
> 
>     * [ ]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez  solucionarse sólo almacenando y buscando?
>       Sí, requiere lógica de negocio para interpretar los datos, analizar su variación, y generar reportes contextualizados y útiles.
> 
>     * [ ]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
>       Si, del conjunto de datos ambientales del ayuntamiento de Granada

No has marcado ninguno de los items, y voy a suponer que no los has hecho. Os rogaría que lo hiciérais, simplemente por ayudaros y orientaros hacia una entrega correcta.

2024-10-05 10:53 UTC, JJ requested changes
No solo no los has resuelto, sino que además parece que no has pulsado en la pestaña "Files" para ver qué comentarios hay. Por favor, hazlo a partir de ahora (y por supuesto resuelve los comentarios)

2024-10-05 10:53 UTC, JJ commented on README.md
> +En la actualidad, los datos ambientales son cruciales para entender la salud pública, la planificación urbana y el bienestar general. Sin embargo, se presenta una serie de desafíos al intentar obtene
Siguen sin resolverse. Tendrías que responder a la pregunta "Son cruciales,¿para quién?"

2024-10-06 14:19 UTC, pablotl0 commented
@JJ revision

2024-10-06 17:13 UTC, JJ commented
Un pull request no se hace para que el profe lo mire. Se hace porque es una de las herramientas para trabajar en desarrollo en equipo. En ese sentido, ¿crees que no poner un título ayuda al resto del equipo a ver la intención del PR?

2024-10-06 17:16 UTC, JJ commented
Te agradecería una vez más que trataras de entender la herramienta con la que estás trabajando, porque la vamos a usar durante el resto de la asignatura (y el resto de tu vida laboral, probablemente, en el futuro previsible). Te lo he advertido ya más arriba, pero por favor hazlo de una vez. Ve a esta pestaña:
![Captura de pantalla de 2024-10-06 19-14-27](https://github.com/user-attachments/assets/926e3abb-4e39-40a7-9471-ce893488fb82)
Files, la que hay más a la derecha. Ahí aparecen los ficheros que se han modificado... Y también los comentarios como este
![Captura de pantalla de 2024-10-06 19-14-13](https://github.com/user-attachments/assets/0e9605d0-09a0-4a42-8b3d-7799aa9f9101)
Los PRs son para eso, para examinar el código enviado, ver que corresponde al título del PR, ver que se ha hecho efectivamente lo que se busca, y si no, se pone un comentario *y la persona que ha hecho el PR responde al mismo*.
Por favor, hazlo como ya te he indicado anteriormente.

2024-10-07 14:52 UTC, pablotl0 commented on README.md
> +El proyecto se centra en la investigación y análisis de los datos ambientales de la ciudad, con el fin de entender cómo estos afectan la calidad de vida y varían a lo largo del tiempo. La meta es obt
Mis clientes son los siguientes :

<img width="479" alt="clientes" src="https://github.com/user-attachments/assets/d9aca6e6-24e6-4adf-b3bf-75e222ff6210">

Cada uno asociado a un problema, que pienso que puede estar relacionado con los datos medioambientales.
He modifcado también en el README el último párrafo escribiendo una breve  conclusión, para no causar confusión.

Perdón por las molestias, ya que no había entendido bien como comunicarme.  Al escribir algunos mensajes en el apartado de conversations en vez de responder en este apartado.

2024-10-07 15:39 UTC, JJ commented on README.md
> +El proyecto se centra en la investigación y análisis de los datos ambientales de la ciudad, con el fin de entender cómo estos afectan la calidad de vida y varían a lo largo del tiempo. La meta es obt
Me temo que ese comentario lo incluí antes de que metieras los clientes. ¿Ves por qué hay que mirar todos los comentarios y resolverlos si se ha hecho en cualquier otro sitio?
Por otro lado, me preocupa lo de "cada uno asociado a un problema". Sabes que hay qeu tratar con un solo problema, ¿no? ¿No estarás hablando de diferentes *visiones* del problema?

2024-10-07 16:43 UTC, pablotl0 commented on README.md
> +El proyecto se centra en la investigación y análisis de los datos ambientales de la ciudad, con el fin de entender cómo estos afectan la calidad de vida y varían a lo largo del tiempo. La meta es obt
Me refería a las distintas visiones del problema.

2024-10-07 17:08 UTC, JJ commented on README.md
> +El proyecto se centra en la investigación y análisis de los datos ambientales de la ciudad, con el fin de entender cómo estos afectan la calidad de vida y varían a lo largo del tiempo. La meta es obt
OK, resuelve el comentario entonces de la forma que estimes conveniente, incluyendo esta información, por ejemplo.

2024-10-07 17:44 UTC, pablotl0 commented on README.md
> +El proyecto se centra en la investigación y análisis de los datos ambientales de la ciudad, con el fin de entender cómo estos afectan la calidad de vida y varían a lo largo del tiempo. La meta es obt
Ya está resuelto.

2024-10-07 17:48 UTC, JJ commented
Por favor, resuélvelos *todos* y cuando lo hagas pídeme revisión explícitamente.

2024-10-07 18:15 UTC, pablotl0 commented
@JJ  revision

2024-10-07 18:27 UTC, JJ commented
> Te agradecería una vez más que trataras de entender la herramienta con la que estás trabajando, porque la vamos a usar durante el resto de la asignatura (y el resto de tu vida laboral, probablemente, en el futuro previsible). Te lo he advertido ya más arriba, pero por favor hazlo de una vez. Ve a esta pestaña: ![Captura de pantalla de 2024-10-06 19-14-27](https://private-user-images.githubusercontent.com/500/373966154-926e3abb-4e39-40a7-9471-ce893488fb82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjU4NjUsIm5iZiI6MTcyODMyNTU2NSwicGF0aCI6Ii81MDAvMzczOTY2MTU0LTkyNmUzYWJiLTRlMzktNDBhNy05NDcxLWNlODkzNDg4ZmI4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxODI2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzY3ZjFhZTQwODE1YTBmZmQ0MGY5NGZlMzdmYzhhMzA5ZTU1ODU2ZGViODMzZTI0ODA1OGI4N2JhNTk5Y2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6MSxqXWnyDHjLgWTqev8fUeqMleh4UXfrEAch93zOEY) _Files changed_, la que hay más a la derecha. Ahí aparecen los ficheros que se han modificado... Y también los comentarios como este ![Captura de pantalla de 2024-10-06 19-14-13](https://private-user-images.githubusercontent.com/500/373966189-0e9605d0-09a0-4a42-8b3d-7799aa9f9101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjU4NjUsIm5iZiI6MTcyODMyNTU2NSwicGF0aCI6Ii81MDAvMzczOTY2MTg5LTBlOTYwNWQwLTA5YTAtNGE0Mi04YjNkLTc3OTlhYTlmOTEwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxODI2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTE5MmUwMjY5YTA5YjlhMmM3YmI1ZGUxMzJiOTk4MWE2MTJlM2E4ZjY3NzYyNDg2Y2E3ZGFmYTA0YmUwNzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uTGW4l5_X1jB01ImT6Yb4zC-4Br3KYGjuyJw0gG8Jok) Los PRs son para eso, para examinar el código enviado, ver que corresponde al título del PR, ver que se ha hecho efectivamente lo que se busca, y si no, se pone un comentario _y la persona que ha hecho el PR responde al mismo_. Por favor, hazlo como ya te he indicado anteriormente. Los comentarios se resuelven cambiando la línea en que se han hecho o indicando por cortesía en qué otro lugar se han hecho y resolviéndolos a mano. Por favor, hazlo así.

Aquí es donde te he comentado cómo se ven los comentarios. En este objetivo hay que aprender, sobre todo, a usar la herramienta. Usar PRs en GitHub y entender los comentarios, verlos y resolverlos, es fundamental en el desarrollo profesional de software. Por favor, intenta entender cómo se hace y por qué.

2024-10-08 07:38 UTC, pablotl0 commented
@JJ revision

2024-10-08 10:58 UTC, JJ commented
De veras que te agradecería que miraras los comentarios. No tienes más que irte a la solapa *files changed* y hacer scroll más abajo en la pantalla. Pero esto ya te lo he dicho, y no parece que hayas hecho caso, así que [aquí tienes el enlace](https://github.com/pablotl0/turismo/pull/1/files#r1785705923). Pincha directamente ahí.

2024-10-08 15:59 UTC, pablotl0 commented on README.md
> +La licencia del proyecto es  [`/LICENSE`](./LICENSE).
¿Qué es lo que falla en la configuración?
Me he basado en lo que han hecho mis compañeros

2024-10-08 17:56 UTC, JJ commented on README.md
> +La licencia del proyecto es  [`/LICENSE`](./LICENSE).
Sería conveniente que leyeras de nuevo [los errores frecuentes en el objetivo 0](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#errores-frecuentes-objetivo-0), que dice al principio

> Es un error demasiado frecuente mirar lo que ha hecho un compañero/a y ponerlo tal cual. Y en general, va a ser un error que va a perjudicar al profesor (que tendrá que revisar dos o tres o 10 veces lo mismo) pero también al estudiante, porque lo que se busca no es que el estudiante entienda formalmente lo que hay que poner, sino que empiece a usar unas metodologías determinadas que le ahorren trabajo (o simplemente le indiquen cómo hacer el trabajo) en un entorno de desarrollo determinado.

> Si se observa el mismo patrón de entrega en varios estudiantes, lo primero que indica es dejadez por parte del estudiante y falta de preocupación por aprender los objetivos de la asignatura. Dado que se puede entregar lo que se desee y el profesor lo corrige, a priori no hay ningún problema porque se le indica al estudiante el error (que en el caso del anterior estudiante puede simplemente haberse pasado por alto por ser el primero o porque hay elementos en la entrega que son correctos) pero a medio plazo no involucrarse con los objetivos de aprendizaje lleva a la frustración ("He puesto lo mismo que el compañero y me lo ha rechazado") trabajo adicional (hay que volver a enviar el objetivo hasta que esté claro que se saben aplicar las metodologías de cada uno de los objetivos) y eventualmente al abandono de la asignatura debido a esa frustración y al retraso que conlleva tener que corregir varias veces el objetivo entregado.

> En general, la mejor estrategia es tratar de entender de forma autónoma los conceptos y metodologías que se incluyen en cada objetivo. Si no se entienden bien, el profesor guiará hasta que se comprendan. Si simplemente se pone lo que ha puesto otro compañero, la corrección del profesor no va a comportar ningún aprendizaje, sino un bucle posiblemente infinito de entregas tomadas de otro compañero/a o de algún lugar.

Esto también lo comenté en el grupo de Telegram. Por otro lado, un poco más abajo en el mismo fichero, dice

> Si no entiendes qué es la configuración, lee [la entrega de la práctica](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#entrega-de-la-pr%C3%A1ctica) y en general trata de entender qué es lo que se pide y, como siempre, por qué. No añadas dos ficheros aleatorios como .gitignore o LICENSE. ¿De qué forma un fichero de licencia es parte de la configuración?

Finalmente, ¿crees que "me he basado en lo que han hecho mis compañeros" contribuye a que yo entienda que has entendido tanto el concepto de "configuración" como el concepto de que los comentarios que hace el profesor tratan de contribuir a que el estudiante lo haga si no es así?

2024-10-08 18:30 UTC, pablotl0 commented on README.md
> +La licencia del proyecto es  [`/LICENSE`](./LICENSE).
Me refiero a que he cambiado muchas veces la documentación adicional y la he puesto de distintas maneras, creyendo que eran propuestas validas. 
Ante los reiterados fallos he creído conveniente investigar como lo han hecho mis compañeros para intentar entender mi fallo. 
Aún así todas las propuestas las he trabajado por mi cuenta incluido la configuración, habiendo comprendido lo que se hace. 
¿Me gustaría saber por qué no es correcta la documentación adicional?

2024-10-08 18:51 UTC, JJ commented on README.md
> +La licencia del proyecto es  [`/LICENSE`](./LICENSE).
El problema está exactamente donde te lo he dicho en el primer comentario en esta serie y también en el hecho de que no hayas resuelto los comentarios, pese a haberte dicho repetidamente que hay que resolver *todos* los comentarios (tras leerlos, claro).

2024-10-08 19:37 UTC, pablotl0 commented on README.md
> +La licencia del proyecto es  [`/LICENSE`](./LICENSE).
¿Tras cambiar la foto esta solucionado?

2024-10-09 05:16 UTC, JJ commented
> Un pull request no se hace para que el profe lo mire. Se hace porque es una de las herramientas para trabajar en desarrollo en equipo. En ese sentido, ¿crees que no poner un título ayuda al resto del equipo a ver la intención del PR?

Esto también te lo dije hace 3 días [en este comentario](https://github.com/pablotl0/turismo/pull/1#issuecomment-2395512967). Por favor, léelos, trata de entender las herramientas que estás utilizando, y actúa en consecuencia.

2024-10-09 07:47 UTC, JJ commented on docs/documentación.pdf
No sé qué intentas hacer aquí, pero ¿quién ha pedido una documentación en PDF?
No se incluyen nunca ficheros binarios en un repositorio. Si hay que incluir alguna imagen se hace usando formatos que se puedan presentar en markdown, como PNG o JPEG. Una captura de pantalla, por ejemplo, se produce directamente en PNG.
Se hace así porque se supone que quien revisa un PR debe ser capaz de ver directamente toda la información en el mismo PR, sin tener que descargar un fichero para poder visualizarlo (como en este caso). Una vez más, entender la herramienta con la que estás trabajando (repositorios de git y GitHub) es tanto o más importante que definir un problema correctamente para poder trabajar con él.

2024-10-09 08:09 UTC, pablotl0 commented
@JJ revision

2024-10-09 08:39 UTC, JJ commented
Esto sigue sin resolver
![Captura de pantalla de 2024-10-09 10-38-56](https://github.com/user-attachments/assets/a718d8c0-b87d-4163-84c2-833b2b49793f)

2024-10-09 09:17 UTC, pablotl0 commented
@JJ Me gustaría saber si he corregido el error y en caso de que no este corregido, ¿por qué?
Ya que he leído la documentación varias veces y no cual es exactamente el fallo.

2024-10-09 09:35 UTC, JJ commented
> @JJ Me gustaría saber si he corregido el error y en caso de que no este corregido, ¿por qué? Ya que he leído la documentación varias veces y no cual es exactamente el fallo.

OK, no corregir algo es una cosa, pero no saber ni siquiera lo que hay que corregir es otra cosa. Te he puesto una captura, te he explicado dónde hay que pulsar, te he explicado por qué es un error, ¿cuales de esas partes no entiendes?

2024-10-09 09:36 UTC, JJ commented
> Esto sigue sin resolver ![Captura de pantalla de 2024-10-09 10-38-56](https://private-user-images.githubusercontent.com/500/374877756-a718d8c0-b87d-4163-84c2-833b2b49793f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjY3OTUsIm5iZiI6MTcyODQ2NjQ5NSwicGF0aCI6Ii81MDAvMzc0ODc3NzU2LWE3MThkOGMwLWI4N2QtNDE2My04NGMyLTgzM2IyYjQ5NzkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwOTM0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzAxYjhjZDZhMmFlMTNmMzYyZGRiYjFmOWVhZDFiYjBlZTc2N2FlZjNlZGE0YjU3ZDA4YTI5MTVmNTQwMzI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mIEZipIRc75ghqKsxFVUYWlQUx-ziCF-9jjVwMxKpkM)

Te agradecería también que leyeras lo que te mando. Te he dicho que no está corregido, ¿por qué me preguntas si está corregido o no?

2024-10-09 09:46 UTC, pablotl0 commented
> > Esto sigue sin resolver ![Captura de pantalla de 2024-10-09 10-38-56](https://private-user-images.githubusercontent.com/500/374877756-a718d8c0-b87d-4163-84c2-833b2b49793f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjY3OTUsIm5iZiI6MTcyODQ2NjQ5NSwicGF0aCI6Ii81MDAvMzc0ODc3NzU2LWE3MThkOGMwLWI4N2QtNDE2My04NGMyLTgzM2IyYjQ5NzkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwOTM0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzAxYjhjZDZhMmFlMTNmMzYyZGRiYjFmOWVhZDFiYjBlZTc2N2FlZjNlZGE0YjU3ZDA4YTI5MTVmNTQwMzI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mIEZipIRc75ghqKsxFVUYWlQUx-ziCF-9jjVwMxKpkM)
> 
> Te agradecería también que leyeras lo que te mando. Te he dicho que no está corregido, ¿por qué me preguntas si está corregido o no?



> ###
> [Oct 9, 2024](#issuecomment-2401827096)

He preguntado al haber cambiado la linea del comentario (borrandola)

2024-10-09 10:35 UTC, merged